Operator:
    handler: Operator Password

User: 
    handler: Operator As User Password

Operator LDAP:
    handler: Operator LDAP

User LDAP:
    handler: User LDAP

Certificate:
    handler: Certificate

_System:
    handler: System

